"""GitHub client for RepoMind – Issues, PRs, files, comments, branches."""
from typing import List, Optional, Dict, Any
from github import Github, GithubException
from github.Repository import Repository
from github.Issue import Issue
from .models import Task
import os
import time

class GitHubClient:
    def __init__(self, token: Optional[str] = None, repo_full_name: Optional[str] = None):
        self.token = token or os.getenv("GITHUB_TOKEN")
        if not self.token:
            raise ValueError("GITHUB_TOKEN required")
        self.gh = Github(self.token)
        self.repo_name = repo_full_name or os.getenv("GITHUB_REPOSITORY", "AgentMindCloud/RepoMind")
        self.repo: Repository = self.gh.get_repo(self.repo_name)

    def get_open_tasks(self, labels: Optional[List[str]] = None) -> List[Task]:
        issues = self.repo.get_issues(state="open", labels=labels or [])
        tasks = []
        for issue in issues:
            if issue.pull_request:
                continue
            tasks.append(Task(
                issue_number=issue.number,
                title=issue.title,
                body=issue.body or "",
                labels=[l.name for l in issue.labels],
                state=issue.state,
                html_url=issue.html_url
            ))
        return tasks

    def get_task(self, number: int) -> Task:
        issue = self.repo.get_issue(number)
        return Task(
            issue_number=issue.number,
            title=issue.title,
            body=issue.body or "",
            labels=[l.name for l in issue.labels],
            state=issue.state,
            html_url=issue.html_url
        )

    def comment_on_issue(self, number: int, body: str) -> None:
        issue = self.repo.get_issue(number)
        issue.create_comment(body)

    def create_issue(self, title: str, body: str, labels: Optional[List[str]] = None) -> int:
        issue = self.repo.create_issue(title=title, body=body, labels=labels or [])
        return issue.number

    def create_or_update_file(self, path: str, content: str, message: str, branch: str = "main") -> str:
        try:
            contents = self.repo.get_contents(path, ref=branch)
            result = self.repo.update_file(path, message, content, contents.sha, branch=branch)
        except GithubException:
            result = self.repo.create_file(path, message, content, branch=branch)
        return result["commit"].sha

    def create_branch(self, branch_name: str, from_branch: str = "main") -> str:
        """Create a new branch from an existing one. Returns the ref name."""
        ref = self.repo.get_git_ref(f"heads/{from_branch}")
        try:
            self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=ref.object.sha)
        except GithubException as e:
            # Branch may already exist – that's ok for our use case
            if e.status != 422:
                raise
        return branch_name

    def create_pull_request(self, title: str, body: str, head: str, base: str = "main", draft: bool = True) -> str:
        """Create a PR. Defaults to draft=True for safety."""
        pr = self.repo.create_pull(title=title, body=body, head=head, base=base, draft=draft)
        return pr.html_url

    def create_draft_pr_from_proposal(
        self,
        title: str,
        body: str,
        branch_prefix: str = "self-improve",
        base: str = "main"
    ) -> str:
        """Convenience: create a unique branch + open a draft PR with the proposal body."""
        ts = int(time.time())
        branch = f"{branch_prefix}/{ts}"
        self.create_branch(branch, from_branch=base)

        # Create a tiny placeholder file so the PR is not empty
        placeholder = f"# Self-Improve Proposal\n\nGenerated by RepoMind SelfImproveAgent.\n\nSee PR body for details.\n"
        self.create_or_update_file(
            path=f"proposals/{ts}.md",
            content=placeholder,
            message=f"chore: self-improve proposal placeholder {ts}",
            branch=branch
        )

        return self.create_pull_request(
            title=title,
            body=body,
            head=branch,
            base=base,
            draft=True
        )

    def add_labels(self, number: int, labels: List[str]) -> None:
        issue = self.repo.get_issue(number)
        issue.add_to_labels(*labels)
